# Generated by Django 5.1.7 on 2025-04-23 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_message_msg_chat_isread_ts_idx'),
        ('product_management', '0003_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, help_text='Denormalized pointer to the last Message in this chat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat_app.message'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['last_message'], name='chat_app_ch_last_me_04123b_idx'),
        ),
    ]
