# Generated by Django 5.1.7 on 2025-04-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_chat_last_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
