# Generated by Django 5.1.7 on 2025-04-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unread_count',
            field=models.PositiveIntegerField(default=0, help_text='Denormalized count of unread messages for the other participant'),
        ),
    ]
