# Generated by Django 5.1.7 on 2025-03-27 19:50

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='User phone number (e.g To contact the seller)', max_length=128, region='GE', unique=True),
        ),
    ]
