# Generated by Django 5.1.7 on 2025-04-03 19:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='User phone number (e.g +995597713815)', max_length=128, region='GE', unique=True),
        ),
    ]
