# Generated by Django 5.1.7 on 2025-04-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://asset.cloudinary.com/dmhb7l2xl/d24a5e6e9e4686cc7c81ee018b79a186', null=True, upload_to='avatars/'),
        ),
    ]
