# Generated by Django 5.1.7 on 2025-04-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://res.cloudinary.com/dmhb7l2xl/image/upload/v1743790870/default-boy-avatar_mca8ah.jpg', null=True, upload_to='avatars/'),
        ),
    ]
