# Generated by Django 5.1.7 on 2025-04-05 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(help_text='Only store age that 18 or are above 18 (e.g 18, 19, 20...)', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default-boy-avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
