# Generated by Django 5.1.7 on 2025-04-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price at time of adding to cart', max_digits=10),
        ),
    ]
