# Generated by Django 5.1.7 on 2025-04-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
