# Generated by Django 5.1.7 on 2025-04-17 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0004_product_average_rating_product_total_reviews_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.OneToOneField(help_text='The owner of this wishlist.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(help_text='The product that was wished for.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='product_management.product')),
                ('wishlist', models.ForeignKey(help_text='The wishlist this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist_app.wishlist')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='wishlist_ap_product_a6622d_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'wishlist'), name='unique_product_wishlist')],
            },
        ),
    ]
